stages:
  - build
  - tests
  - publish_images

variables:
  ETCD_CONTAINER_VERSION: '0.1.0'
  ETCD_VERSION: 'v3.4.14'

#-----------------------------------------
build_image:
  stage: build
  tags:
    - shell
  variables:
    BUILD_OPTS: '--network=internal_bridge --force-rm --no-cache'
  script:
    - docker build ${BUILD_OPTS} -t article714/etcd-container:${ETCD_CONTAINER_VERSION} -t article714/etcd-container:latest   --build-arg ETCD_CONTAINER_VERSION=${ETCD_CONTAINER_VERSION}  --build-arg ETCD_VERSION=${ETCD_VERSION} .

test_image:
  stage: tests
  tags:
    - docker
  image: article714/etcd-container:${ETCD_CONTAINER_VERSION}
  script:
    - /usr/bin/etcd --version
    - /usr/bin/etcdctl version
    - runsvdir -P /container/services &
    - sv status etcd
    - /usr/bin/etcdctl endpoint status --endpoints=[127.0.0.1:2379]

publish_image:
  stage: publish_images
  tags:
    - shell
  only:
    refs:
      - production
  script:
    - docker push article714/etcd-container:${ETCD_CONTAINER_VERSION}
    - docker push article714/etcd-container:latest
